package:
  name: maestro
  version: "0.0.2"
source:
  git_url: https://github.com/chenfeiwang/MAESTRO.git
# source:
#   path: ../../
# build:
#   entry_points:
#     - strap = strap:main
requirements:
  build:
    - python =3.7
    - numpy =1.17
    - scipy =1.3.0
    - h5py =2.9.0
    - pytables =3.5.2
    - setuptools
    - snakemake =5.4.5
    - rseqc =3.0.0
    - star =2.5.1b
    - bwa =0.7.17
    - samtools =1.9
    - bedtools =2.28.0
    - rsem =1.3.2
    - picard =2.20.2
    - macs2 =2.2.5
    - ucsc-bedsort
    - ucsc-bedgraphtobigwig
    - umap-learn
    - r-BiocManager
    - r-devtools
    - r-hdf5r
    - r-SDMTools
    - r-optparse
    - r-stringi
    - r-Seurat =3.0.1
    - bioconductor-biomaRt
    - bioconductor-MAST
    - bioconductor-AnnotationDbi
    - bioconductor-BiocGenerics
    - bioconductor-GO.db
    - bioconductor-pcaMethods
    - bioconductor-GenomicRanges
    - bioconductor-BiocGenerics
    - bioconductor-Rsamtools
    - bioconductor-chromVAR
    - bioconductor-genefilter
  run:
    - python =3.7
    - numpy =1.17
    - scipy =1.3.0
    - h5py =2.9.0
    - pytables =3.5.2
    - setuptools
    - snakemake =5.4.5
    - rseqc =3.0.0
    - star =2.5.1b
    - bwa =0.7.17
    - samtools =1.9
    - bedtools =2.28.0
    - rsem =1.3.2
    - picard =2.20.2
    - macs2 =2.2.5
    - ucsc-bedsort
    - ucsc-bedgraphtobigwig
    - umap-learn
    - r-BiocManager
    - r-devtools
    - r-hdf5r
    - r-SDMTools
    - r-optparse
    - r-stringi
    - r-Seurat =3.0.1
    - bioconductor-biomaRt
    - bioconductor-MAST
    - bioconductor-AnnotationDbi
    - bioconductor-BiocGenerics
    - bioconductor-GO.db
    - bioconductor-pcaMethods
    - bioconductor-GenomicRanges
    - bioconductor-BiocGenerics
    - bioconductor-Rsamtools
    - bioconductor-chromVAR
    - bioconductor-genefilter
about:
  home: https://github.com/chenfeiwang/MAESTRO
  license: GPL-3.0
  summary: MAESTRO(Model-based AnalysEs of Single-cell Transcriptome and RegulOme) is a comprehensive single-cell RNA-seq and ATAC-seq analysis suit built using snakemake. 
