# Directory where fastq files are stored
fastqdir: /homes/cwang/projects/ATAC/data/Data_cancer/CFCE_LUCAP/Raw/LUCAP_49_IDX
# Sample name of fastq file
fastqprefix: LUCAP_49_IDX
# Species to use [GRCh38, GRCm38] (GRCh38 for human and GRCm38 for mouse)
species: GRCh38
# Platform of single cell ATAC-seq [10xGenomics, sci-ATAC-seq, microfluidic]
platform: 10xGenomics
# The prefix of output files
outprefix: LUCAP_49
# The core number
cores: 8
# Flag to provide custom peaks [TRUE, FALSE]
custompeaks: TRUE
# File location of custom peaks
custompeaksloc: /homes/cwang/annotations/strap/hg38_rDHS_dynamic.bed
# Gene threshold, only consider the peaks within 100KB of the TSS region when calculate gene score.
genedistance: 100000
# TF threshold, only consider the TFs with at least 1% overlap with peak regions
tfpercent: 0.01

# Reference genome 
genome:
  # Genome index directory for BWA
  fasta: /homes/cwang/annotations/refdata-cellranger-atac-GRCh38-1.0.1/fasta/genome.fa
  # genome annotation file from 10xGenomics required for Cell Ranger ATAC
  cellranger: /homes/cwang/annotations/refdata-cellranger-atac-GRCh38-1.0.1