# Directory where fastq files are stored
fastqdir: /mnt/Storage/home/sundongqing/Project/Single_cell/Analysis/10xPBMC_1k/pbmc_1k_v2_fastqs
# Sample name of fastq file (only for platform of "10x-genomics", for example, 
# if there is a file named pbmc_1k_v2_S1_L001_I1_001.fastq.gz, the sample name is "pbmc_1k_v2". )
fastqprefix: pbmc_1k_v2
# Species to use [GRCh38, GRCm38] (GRCh38 for human and GRCm38 for mouse)
species: GRCh38
# Platform of single cell RNA-seq [Smartseq2, 10x-genomics, Dropseq]
platform: 10x-genomics
# The prefix of output files
outprefix: pbmc_1k_v2
# Run RSeQC or not [True, False]
rseqc: False
# Number of cores to use
cores: 8
# annotation to run rabit
rabitlib: /home1/wangchenfei/Project/SingleCell/scATAC/Code/MAESTRO/MAESTRO/annotations/Rabit_lib

# Reference genome 
genome:
  # Genome index directory for STAR
  mapindex: /home1/wangchenfei/annotations/refdata-cellranger-GRCh38-3.0.0/star
  # .gtf format genome annotation file
  gtf: /home1/wangchenfei/annotations/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf
  # genome annotation file from 10x-genomics required for Cell Ranger
  cellranger: /home1/wangchenfei/annotations/refdata-cellranger-GRCh38-3.0.0
  # the prefix of transcript references for RSEM used by rsem-prepare-reference
  rsem: /home1/wangchenfei/annotations/hg38/RSEM_ref/GRCh38

# Information about barcode (only for platform of "Dropseq")
barcode:
  # The start site of each barcode (deinterleave linkers and connect barcodes and UMI)
  # If there's no need to remove linkers, set "start" as NULL.
  start: "0,48,86"
  # The end site of each barcode (deinterleave linkers and connect barcodes and UMI)
  end: "18,56,150"
  # The length of umi (after linker removal)
  umilength: 8
  # The length of cell barcode (after linker removal)
  barcodelength: 12

# Specify the barcode fastq file and reads fastq file (only for platform of "Dropseq")
fastq:
  # barcode fastq file
  barcode: test_2
  # transcript fastq file
  transcript: test_1
