# Directory where fastq files are stored
fastqdir: /home/cw254/projects/MAESTRO/snakemake/RNA/10X/pbmc8k
# Sample name of fastq file (only for platform of "10x-genomics", for example, 
# if there is a file named pbmc_1k_v2_S1_L001_I1_001.fastq.gz, the sample name is "pbmc_1k_v2". )
fastqprefix: pbmc8k
# Species to use [GRCh38, GRCm38] (GRCh38 for human and GRCm38 for mouse)
species: GRCh38
# Platform of single cell RNA-seq [Smartseq2, 10x-genomics, Dropseq]
platform: 10x-genomics
# The prefix of output files
outprefix: 10X_PBMC_8K
# Number of cores to use
cores: 8
# annotation to run rabit
rabitlib: /home/cw254/annotations/rabit

# Reference genome 
genome:
  # Genome index directory for STAR
  mapindex: /home/cw254/annotations/refdata-cellranger-hg38-3.0.0/star
  # .gtf format genome annotation file
  gtf: /home/cw254/annotations/refdata-cellranger-hg38-3.0.0/genes/genes.gtf
  # genome annotation file from 10x-genomics required for Cell Ranger
  cellranger: /home/cw254/annotations/refdata-cellranger-hg38-3.0.0

# Information about barcode (only for platform of "Dropseq")
barcode:
  # The start site of each barcode (deinterleave linkers and connect barcodes and UMI)
  # If there's no need to remove linkers, set "start" as NULL.
  start: 
  # The end site of each barcode (deinterleave linkers and connect barcodes and UMI)
  end: 
  # The range of umi (after linker removal)
  umilength: 
  # The range of cell barcode (after linker removal)
  barcodelength: 

# Specify the barcode fastq file and reads fastq file (only for platform of "Dropseq")
fastq:
  # barcode fastq file
  barcode: 
  # transcript fastq file
  transcript: 