# Directory where fastq files are stored
fastqdir: /homes/cwang/projects/MAESTRO/snakemake/RNA/10X
# Sample name of fastq file (only for platform of "10x-genomics", for example, 
# if there is a file named pbmc_1k_v2_S1_L001_I1_001.fastq.gz, the sample name is "pbmc_1k_v2". )
fastqprefix: pbmc8k_fastqs
# Species to use [GRCh38, mmu] (GRCh38 for human and mmu for mouse)
species: GRCh38
# Platform of single cell RNA-seq [Smartseq2, 10x-genomics, Dropseq]
platform: 10x-genomics
# The prefix of output files
outprefix: 10X_PBMC_8K
# Number of cores to use
cores: 8
# annotation to run rabit
rabitlib: /homes/cwang/annotations/rabit

# Reference genome 
genome:
  # Genome index directory for STAR
  mapindex: /homes/cwang/annotations/refdata-cellranger-hg38-1.2.0/star
  # gtf format genome annotation file
  gtf: /homes/cwang/annotations/refdata-cellranger-hg38-1.2.0/genes/genes.gtf
  # directory of cellranger annotations (only for platform of "10x-genomics")
  cellranger: /homes/cwang/annotations/refdata-cellranger-hg38-1.2.0

# Information about barcode (only for platform of "Dropseq")
barcode:
  # The start site of each barcode (deinterleave linkers and connect barcodes and UMI)
  start: 
  # The end  site of each barcode (deinterleave linkers and connect barcodes and UMI)
  end: 
  # The range of umi (after linker removal)
  umirange: 
  # The range of cell barcode (after linker removal)
  barcoderange: 

# Specify the barcode fastq file and reads fastq file (only for platform of "Dropseq")
fastq:
  # barcode fastq file
  barcode: 
  # transcript fastq file
  transcript:
