# Directory where fastq files are stored
fastqdir: {{ fastqdir }}

# Sample name of fastq file (required for the platform of '10x-genomics' or 'sci-ATAC-seq'). 
# When the platform is '10x-genomics', if there is a file named pbmc_1k_v2_S1_L001_I1_001.fastq.gz, the prefix is 'pbmc_1k_v2'.
# If the platform is 'sci-ATAC-seq', there are two ways to provide fastq files. 
# The first is to provide pair-end sequencing results which contain two fastq files -- prefix_1.fastq and prefix_2.fastq. 
# If in this way, the barcode for each read needs to be included in the reads ID (the first line of each read) 
# in the format of '@ReadName:CellBarcode:OtherInformation'. For example, @rd.1:TCTCCCGCCGAGGCTGACTGCATAAGGCGAAT:SHEN-MISEQ02:1:1101:15311:1341. 
# The other way is to provide 10x-like fastq files which should contain three fastq files -- prefix_R1.fastq, prefix_R2.fastq and prefix_R3.fastq. 
# In this way, read1, barcode and read2 are associated with R1, R2, R3, respectively.
fastqprefix: {{ fastqprefix }}

# Species to use [GRCh38, GRCm38] (GRCh38 for human and GRCm38 for mouse)
species: {{ species }}

# Platform of single cell ATAC-seq [10x-genomics, sci-ATAC-seq, microfluidic]
platform: {{ platform }}

# The prefix of output files. DEFAULT: MAESTRO.
outprefix: {{ outprefix }}

# If the platform is 'sci-ATAC-seq' or '10x-genomics', please specify the barcode library (whitelist) 
# so that the pipeline can correct cell barcodes with 1 base mismatched. 
# Otherwise, the pipeline will automatically output the barcodes with enough read count (>1000).
# The 10X Chromium whitelist file can be found inside the CellRanger-ATAC distribution. 
# For example, in CellRanger-ATAC 1.1.0, the whitelist is 'cellranger-atac-1.1.0/cellranger-atac-cs/1.1.0/lib/python/barcodes/737K-cratac-v1.txt'. 
whitelist: {{ whitelist }}

# The core number
cores: {{ cores }}

# Cell signature file used to annotate cell types. MAESTRO provides several sets of built-in cell signatures. 
# Users can choose from ['human.immune.CIBERSORT', 'mouce.brain.ALLEN', 'mouse.all.facs.TabulaMuris', 'mouse.all.droplet.TabulaMuris']. 
# Custom cell signatures are also supported. In this situation, users need to provide the file location of cell signatures, 
# and the signature file is tab-seperated without header. The first column is cell type, and the second column is signature gene.
signature: {{ signature }}

# Whether or not to provide custom peaks. [False, True]
# If custompeaks is set as True, users need to provide the file location of peak file through custompeaksloc 
# and then MAESTRO will merge the custom peak file and the peak file called from all fragments using MACS2. 
# By default (False), the pipeline will use the peaks called using MACS2. DEFAULT: False.
custompeaks: {{ custompeaks }}

# IF custompeaks = TRUE, provide the file location of custom peaks
# The peak file is BED formatted with tab seperated. 
# The first column is chromsome, the second is chromStart, and the third is chromEnd.
custompeaksloc: {{ custompeaksloc }}

# Whether or not to call peaks from short fragments (shorter than 150bp). [True, False]
# If it's set as True, MAESTRO will merge the peaks called from all fragments and those called from short fragments, 
# and then use the merged peak file for further analysis.
# If not (by default), the pipeline will only use peaks called from all fragments.
shortpeaks: {{ shortpeaks }}

# The RP model to use to calaculate gene score. [Simple, Adjusted]
# For each gene, simple model summarizes the impact of all regulatory elements within the up/dowm-stream of TSS. 
# On the basis of simple model, adjusted model includes the regulatory elements within the exon region, 
# and also excludes the regulatory elements overlapped with another gene (the promoter and exon of a nearby gene). 
# See the MAESTRO paper for more details. DEFAULT: Adjusted.
rpmodel: {{ rpmodel }}

# Gene score decay distance, could be optional from 1kb (promoter-based regulation) and 10kb(enhancer-based regulation), default is 10kb
genedistance: {{ genedistance }}

# Path of the giggle annotation file required for regulator identification. 
# Please download the annotation file from http://cistrome.org/~chenfei/MAESTRO/giggle.tar.gz and decompress it.
giggleannotation: {{ giggleannotation }}

# Whether or not to call peaks by cluster [True, False]
# If it's set True, MAESTRO will split the bam file according to clustering result, and then call peaks for each cluster.
# By default (not set), MAESTRO will skip this step.
clusterpeaks : {{ clusterpeaks }}


# Quality control cutoff
cutoff:
  # Minimum number of peaks included in each cell. DEFAULT: 100.
  peak: {{ peak }}
  # Cutoff for the number of count in each cell. DEFAULT: 1000.
  count: {{ count }}
  # Cutoff for fraction of reads in promoter in each cell. DEFAULT: 0.2.
  frip: {{ frip }}
  # Minimum number of cells covered by each peak. DEFAULT: 10.
  cell: {{ cell }}


# Reference genome 
genome:
  # Genome fasta file for minimap2. Users can just download the fasta file 
  # from http://cistrome.org/~chenfei/MAESTRO/Refdata_scATAC_MAESTRO_GRCh38_1.1.0.tar.gz and decompress it. 
  # For example, 'Refdata_scATAC_MAESTRO_GRCh38_1.1.0/GRCh38_genome.fa'.
  fasta: {{ fasta }}
