# Directory where fastq files are stored
fastqdir: {{ fastqdir }}
# Sample name of fastq file
fastqprefix: {{ fastqprefix }}
# Species to use [GRCh38, GRCm38] (GRCh38 for human and GRCm38 for mouse)
species: {{ species }}
# Platform of single cell ATAC-seq [10x-genomics, sci-ATAC-seq, microfluidic]
platform: {{ platform }}
# The prefix of output files
outprefix: {{ outprefix }}
# Please specify the barcode library if the platform is sci-ATAC-seq, or the pipeline will automatically output the barcodes with enough read counts (>1000).
whitelist: {{ whitelist }}
# The core number
cores: {{ cores }}
# Flag to provide custom cell signatures [TRUE, FALSE]
signature: {{ signature }}
# If signature = TRUE, provide the file location of custom cell signatures.
# The signature file is tab-seperated. The first column is cell type, and the second column is signature gene.
signaturefile: {{ signaturefile }}
# Flag to provide custom peaks [TRUE, FALSE]
custompeaks: {{ custompeaks }}
# IF custompeaks = TRUE, provide the file location of custom peaks
custompeaksloc: {{ custompeaksloc }}
# Whether or not to call peaks from short fragment (less than 50bp)
shortpeaks: {{ shortpeaks }}
# Gene score decay distance, could be optional from 1kb (promoter-based regulation) and 10kb(enhancer-based regulation), default is 10kb
genedistance: {{ genedistance }}
# Path of the giggle annotation file.
giggleannotation: {{ giggleannotation }}

# Quality control cutoff
cutoff:
  # Minimum number of peaks included in each cell. DEFAULT: 100.
  peak: {{ peak }}
  # Cutoff for the number of count in each cell. DEFAULT: 1000.
  count: {{ count }}
  # Cutoff for fraction of reads in promoter in each cell. DEFAULT: 0.2.
  frip: {{ frip }}
  # Minimum number of cells covered by each peak. DEFAULT: 10.
  cell: {{ cell }}

# Reference genome 
genome:
  # Genome index directory for BWA
  fasta: {{ fasta }}
  # genome annotation file from 10x-genomics required for Cell Ranger ATAC
  # cellranger: {{ cellranger }}
