# Directory where fastq files are stored
fastqdir: /home/cw254/projects/MAESTRO/snakemake/ATAC/10X/atac_v1_pbmc_10k_fastqs
# Sample name of fastq file
fastqprefix: atac_v1_pbmc_10k
# Species to use [GRCh38, GRCm38] (GRCh38 for human and GRCm38 for mouse)
species: GRCh38
# Platform of single cell ATAC-seq [10x-genomics, sci-ATAC-seq, microfluidic]
platform: 10x-genomics
# The prefix of output files
outprefix: 10X_PBMC_10K
# Please specify the barcode library if the platform is sci-ATAC-seq, or the pipeline will automatically output the barcodes with enough reads count (>1000).
barcodelib: 
# The core number
cores: 8
# Flag to provide custom peaks [TRUE, FALSE]
custompeaks: FALSE
# IF custompeaks = TRUE, provide the file location of custom peaks
custompeaksloc: 
# Whether or not to call peaks from short fragment (less than 50bp)
shortpeaks: FALSE
# Gene score decay distance, could be optional from 1kb (promoter-based regulation) and 10kb(enhancer-based regulation), default is 10kb
genedistance: 10000
# Path of the giggle annotation file.
giggleannotation: /home/cw254/annotation/giggle 

# Reference genome 
genome:
  # Genome index directory for BWA
  fasta: /home/cw254/annotation/refdata-cellranger-atac-GRCh38-1.1.0/fasta/genome.fa
  # genome annotation file from 10x-genomics required for Cell Ranger ATAC
  cellranger: /home/cw254/annotation/refdata-cellranger-atac-GRCh38-1.1.0
