channels:
  - bioconda
  - conda-forge
dependencies:
  - star = 2.7.1a
  - bwa = 0.7.17
  - samtools = 1.9
  - bedtools = 2.28.0
  - stringtie = 1.3.6
  - snakemake = 5.4.5
  - picard = 2.20.2
  - r-Seurat = 2.3.4
  - bioconductor-biomaRt
  - bioconductor-MAST