package:
  name: strap
  version: "0.0.1"
# source:
#   git_url: https://github.com/chenfeiwang/STRAP.git
source:
  path: ../../
build:
  entry_points:
    - strap = strap:main
requirements:
  build:
    - python =3.6
    - numpy =1.16.4
    - scipy =1.3.0
    - setuptools
    - snakemake =5.4.5
    - rseqc =3.0.0
    - star =2.5.1b
    - bwa =0.7.17
    - samtools =1.9
    - bedtools =2.28.0
    - stringtie =1.3.6
    - picard =2.20.2
    - r-Seurat =2.3.4
    - bioconductor-biomaRt
    - bioconductor-MAST
  run:
    - python =3.6
    - numpy =1.16.4
    - scipy =1.3.0
    - setuptools
    - snakemake =5.4.5
    - rseqc =3.0.0
    - star =2.5.1b
    - bwa =0.7.17
    - samtools =1.9
    - bedtools =2.28.0
    - stringtie =1.3.6
    - picard =2.20.2
    - r-Seurat =2.3.4
    - bioconductor-biomaRt
    - bioconductor-MAST
about:
  home: https://github.com/chenfeiwang/STRAP
  license: GPL-3.0
  summary: STRAP is a comprehensive quality control, analysis and visualization pipeline for scATAC-seq and scRNA-seq.
