package:
  name: strap
  version: "0.0.1"
source:
  path: ../../
build:
  entry_points:
    - strap = strap:main
requirements:
  build:
    - python =3.6
    - setuptools
    - snakemake =5.4.5
    - star =2.7.1a
    - bwa =0.7.17
    - samtools =1.9
    - bedtools =2.28.0
    - stringtie =1.3.6
    - picard =2.20.2
    - r-Seurat =2.3.4
    - bioconductor-biomaRt
    - bioconductor-MAST
  run:
    - python =3.6
    - setuptools
    - snakemake =5.4.5
    - star =2.7.1a
    - bwa =0.7.17
    - samtools =1.9
    - bedtools =2.28.0
    - stringtie =1.3.6
    - picard =2.20.2
    - r-Seurat =2.3.4
    - bioconductor-biomaRt
    - bioconductor-MAST
about:
  home: https://bitbucket.org/chenfeiwang/strap
  license: MIT License
  summary: STRAP is a comprehensive quality control, analysis and visualization pipeline for scATAC-seq and scRNA-seq.
